Various fixes for later Java and Jenkins versions
Old versions of the amqp-client lib raises exceptions with
latest Java 8 version. Probably due to sharpened policies
on how tls certs are handled:

javax.net.ssl.SSLHandshakeException: No appropriate protocol
  (protocol is disabled or cipher suites are inappropriate)

Fix by updating amqp-client to 5.6.0, same version as used by
the eiffel & mq-notifier-plugin.

+ Introduce pom fixes to allow surefire to run with jmockit.
+ Upgrade plugin parent to 3.50 and needed java version to 8.